apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster1-installation.yaml
- cluster2-installation.yaml
- gw-lifecycle-manager-cluster1.yaml
- gw-lifecycle-manager-cluster2.yaml
